import fs from 'node:fs';import assert from 'node:assert/strict';
import {stageFixture,functionSetup} from '../../production/tests/fixtures/s05.ts';import {functionOperationRef,functionProfile} from '../../production/src/modules/function-operations.ts';import {Graph} from '../../production/src/model/graph.ts';import {compile} from '../../production/src/generation/compiler.ts';import {asNetwork} from '../../production/src/sdk/networks.ts';
const out='.verification/s05-resource-rereview-01';const original=JSON.parse(fs.readFileSync('production/evidence/s05/review-01/independent-review/cross-stage-uniform-01.json','utf8')),setup=functionSetup(),originalGraph=new Graph(original.document,setup.fixed,setup.identity),originalBefore=originalGraph.capture(),originalResult=compile(originalBefore,setup.fixed,functionProfile);assert.deepEqual(originalGraph.capture(),originalBefore);assert.equal(originalResult.status,'success');
const cases=[{name:'exact-original-review-document',expectedActive:2,expectedPosition:[0.25,0.25,0.25,0.25],overrideResource:original.resources[0].resourceId,overrideValue:0.125,overridePosition:[0.125,0.125,0.125,0.125],document:original.document,generated:originalResult}];
const refused=stageFixture(),refusedBefore=refused.graph.capture();assert.throws(()=>refused.graph.change('Unsupported nested Source remains rejected',d=>{const id=d.createSource('forbidden','glsl.float',0.25,true,{kind:'uniform'});d.addReferenceNode(refused.body,'source',id,undefined,functionOperationRef('source'));}),/SOURCE_ADMISSION/);assert.deepEqual(refused.graph.capture(),refusedBefore);
for(const shared of [false,true])for(const mode of ['expand','function','nested','mixed'])for(const reversed of [false,true]){
 const s=stageFixture(),ids=[];s.graph.change('Independent resource definitions',d=>{ids.push(d.createSource('A','glsl.float',shared?0.125:0.3125,true,{kind:'uniform'}));ids.push(d.createSource('B','glsl.float',shared?0.25:0.6875,true,{kind:'uniform'}));if(mode==='expand'||mode==='mixed')d.emissionMode(s.body,'expand',functionProfile);});
 for(const [index,stage] of s.graph.capture().document.graph.stages.entries()){
  const call=stage.network.nodes.find(n=>s.fixed.node(n.type)?.modelRole==='call');
  s.graph.change('Independent noncommutative resource weighting',d=>{
   if(shared){const first=d.addReferenceNode(stage.network.id,'source',ids[index],undefined,functionOperationRef('source')),second=d.addReferenceNode(stage.network.id,'source',ids[1-index],undefined,functionOperationRef('source')),twice=d.add(stage.network.id,functionOperationRef('add'),[0,0]),sum=d.add(stage.network.id,functionOperationRef('add'),[0,0]);for(const key of ['a','b'])d.connect(stage.network.id,{nodeId:second,portKey:'value'},{nodeId:twice,portKey:key});d.connect(stage.network.id,{nodeId:first,portKey:'value'},{nodeId:sum,portKey:'a'});d.connect(stage.network.id,{nodeId:twice,portKey:'value'},{nodeId:sum,portKey:'b'});d.connect(stage.network.id,{nodeId:sum,portKey:'value'},{nodeId:call.id,portKey:'value'},true);}
   else{const source=d.addReferenceNode(stage.network.id,'source',ids[index],undefined,functionOperationRef('source'));d.connect(stage.network.id,{nodeId:source,portKey:'value'},{nodeId:call.id,portKey:'value'},true);}
  });
  if(mode==='nested'||mode==='mixed'){s.graph.change('Nest independent invocation',d=>d.encapsulate(stage.network.id,[call.id]));const outer=s.graph.capture().document.graph.resources.find(r=>asNetwork(r,s.fixed)?.network.nodes.some(n=>n.id===call.id));s.graph.change('Outer function',d=>d.emissionMode(asNetwork(outer,s.fixed).network.id,'function',functionProfile));}
 }
 const document=structuredClone(s.graph.capture().document);if(reversed)document.graph.stages.reverse();const graph=new Graph(document,s.fixed,s.identity),before=graph.capture(),generated=compile(before,s.fixed,functionProfile);assert.equal(generated.status,'success',JSON.stringify(generated.diagnostics));assert.deepEqual(graph.capture(),before);const name=(shared?'shared-weighted-reversed-encounter':'distinct')+'-'+mode+'-'+(reversed?'pixel-first':'vertex-first'),expected=shared?0.625:0.3125,override=shared?0.5625:0.125;cases.push({name,expectedActive:2,expectedPosition:[expected,expected,expected,expected],overrideResource:ids[0],overrideValue:shared?0.0625:0.125,overridePosition:[override,override,override,override],document,generated});
}
fs.writeFileSync(out+'/independent-uniform-candidates-02.json',JSON.stringify({originalDocumentUnchanged:true,nestedSourceAdmission:{rejected:'SOURCE_ADMISSION',graphUnchanged:true,reason:'Existing root-only Source policy was respected; no admission bypass in probe or repair.'},caseCount:cases.length,cases},null,2));console.log(JSON.stringify({caseCount:cases.length,nestedSourceAdmission:'PASS_EXPECTED_REJECTION',names:cases.map(c=>c.name)}));
