import fs from 'node:fs';import assert from 'node:assert/strict';
import {stageFixture,functionSetup} from '../../production/tests/fixtures/s05.ts';
import {functionOperationRef,functionProfile} from '../../production/src/modules/function-operations.ts';
import {Graph} from '../../production/src/model/graph.ts';import {compile} from '../../production/src/generation/compiler.ts';import {asNetwork,callResource} from '../../production/src/sdk/networks.ts';
const out='.verification/s05-resource-rereview-01';const original=JSON.parse(fs.readFileSync('production/evidence/s05/review-01/independent-review/cross-stage-uniform-01.json','utf8'));
const setup=functionSetup(),originalGraph=new Graph(original.document,setup.fixed,setup.identity),originalBefore=originalGraph.capture(),originalResult=compile(originalBefore,setup.fixed,functionProfile);assert.deepEqual(originalGraph.capture(),originalBefore);assert.equal(originalResult.status,'success');
const cases=[{name:'exact-original-review-document',expectedActive:2,expectedPosition:[0.25,0.25,0.25,0.25],vertexResource:original.resources[0].resourceId,overridePosition:[0.125,0.125,0.125,0.125],document:original.document,generated:originalResult}];
for(const shared of [false,true])for(const mode of ['expand','function','nested','mixed'])for(const reversed of [false,true]){
 const s=stageFixture();const stages=s.graph.capture().document.graph.stages;const pixel=stages.find(st=>st.key==='pixel'),pixelCall=pixel.network.nodes.find(n=>s.fixed.node(n.type)?.modelRole==='call');
 if(!shared)s.graph.change('Independent pixel captured source',d=>d.makeIndependent(pixel.network.id,pixelCall.id));
 const defs=s.graph.capture().document.graph.resources.filter(r=>asNetwork(r,s.fixed));const sources=[];let vertexResource='';
 s.graph.change('Independent captured resource definitions',d=>{for(const resource of defs){const data=asNetwork(resource,s.fixed),isVertex=resource.id===callResource(stages.find(st=>st.key==='vertex').network.nodes.find(n=>s.fixed.node(n.type)?.modelRole==='call'),s.fixed),value=isVertex?0.3125:0.6875,id=d.createSource('captured-'+resource.id,'glsl.float',value,true,{kind:'uniform'});sources.push({id,value});if(isVertex)vertexResource=id;const source=d.addReferenceNode(data.network.id,'source',id,undefined,functionOperationRef('source'));const output=data.network.nodes.find(n=>s.fixed.node(n.type)?.modelRole==='network-output');d.connect(data.network.id,{nodeId:source,portKey:'value'},{nodeId:output.id,portKey:'value'},true);d.emissionMode(data.network.id,mode==='expand'||mode==='mixed'?'expand':'function',functionProfile);}});
 if(mode==='nested'||mode==='mixed')for(const stage of s.graph.capture().document.graph.stages){const call=stage.network.nodes.find(n=>s.fixed.node(n.type)?.modelRole==='call');s.graph.change('Wrap capture',d=>d.encapsulate(stage.network.id,[call.id]));const outer=s.graph.capture().document.graph.resources.find(r=>asNetwork(r,s.fixed)?.network.nodes.some(n=>n.id===call.id));s.graph.change('Outer helper',d=>d.emissionMode(asNetwork(outer,s.fixed).network.id,'function',functionProfile));}
 const document=structuredClone(s.graph.capture().document);if(reversed)document.graph.stages.reverse();const graph=new Graph(document,s.fixed,s.identity),before=graph.capture(),generated=compile(before,s.fixed,functionProfile);assert.equal(generated.status,'success',JSON.stringify(generated.diagnostics));assert.deepEqual(graph.capture(),before);const name='captured-'+(shared?'shared':'distinct')+'-'+mode+'-'+(reversed?'pixel-first':'vertex-first');cases.push({name,expectedActive:shared?1:2,expectedPosition:[0.3125,0.3125,0.3125,0.3125],vertexResource,overridePosition:[0.125,0.125,0.125,0.125],document,generated});
}
fs.writeFileSync(out+'/independent-uniform-candidates-01.json',JSON.stringify({originalDocumentUnchanged:true,caseCount:cases.length,cases},null,2));console.log(JSON.stringify({cases:cases.map(c=>({name:c.name,bindings:c.generated.bindingSchema,expectedActive:c.expectedActive}))}));
