const fs=require('fs'),path=require('path'),cp=require('child_process'),crypto=require('crypto');const root=process.cwd().replaceAll('\\','/'),out=root+'/.verification/s05-drag-performance-review-01',runtime=out+'/runtime',input=root+'/production/evidence/s05/drag-performance-repair-01/harness';const h=b=>crypto.createHash('sha256').update(b).digest('hex'),rows=[];
const edit=(src,dst,fn)=>{const before=fs.readFileSync(src,'utf8'),after=fn(before);fs.writeFileSync(dst,after,{flag:'wx'});rows.push({source:src,sourceSha256:h(Buffer.from(before)),output:dst,outputSha256:h(Buffer.from(after)),adaptation:'Absolute checkout/runtime/output paths only; measurement/assertions unchanged.'});};
edit(input+'/prepare-performance.cjs',out+'/prepare-performance.cjs',s=>s.replaceAll('C:/Users/user/source/Grape',root).replace("out=root+'/production/evidence/s05/drag-performance-repair-01/performance-01'","out=__dirname+'/performance-01'").replace("root+'/production/node_modules/@noble/hashes'",JSON.stringify(runtime+'/production/node_modules/@noble/hashes')));
cp.execFileSync(process.execPath,[out+'/prepare-performance.cjs'],{cwd:out,stdio:'inherit'});
const perf=out+'/performance';fs.copyFileSync(input+'/performance/before-manifest.json',perf+'/before-manifest.json');fs.copyFileSync(input+'/performance/after-manifest.json',perf+'/after-manifest.json');
const instrument=fs.readFileSync(perf+'/instrument.cjs','utf8');fs.writeFileSync(perf+'/instrument-original.cjs',instrument,{flag:'wx'});fs.writeFileSync(perf+'/instrument.cjs',instrument.replaceAll('C:/Users/user/source/Grape',runtime));
edit(input+'/performance/build.cjs',perf+'/build.cjs',s=>s.replaceAll('C:/Users/user/source/Grape',runtime).replace("out=root+'/production/evidence/s05/drag-performance-repair-01/performance-01'","out="+JSON.stringify(out+'/performance-01')));
edit(input+'/performance/measure.cjs',perf+'/measure.cjs',s=>s.replaceAll('C:/Users/user/source/Grape',runtime));edit(input+'/performance/aggregate.cjs',perf+'/aggregate.cjs',s=>s.replaceAll('C:/Users/user/source/Grape/production/evidence/s05/drag-performance-repair-01/performance-01',out+'/performance-01'));
for(const name of ['archive-public-numeric-01.ts','archive-origin-replay-01.ts'])edit(input+'/'+name,out+'/'+name,s=>s.replaceAll('C:/Users/user/source/Grape',runtime));
fs.writeFileSync(out+'/harness-adaptations-01.json',JSON.stringify({rows,note:'prepare source reads managed exact-R and git R5; copied dependencies runtime only. instrument-original preserved. Fresh performance and archive evidence only.'},null,2)+'\n',{flag:'wx'});
for(const n of ['instrument.cjs','build.cjs']){const p=cp.spawnSync(process.execPath,[perf+'/'+n],{cwd:perf,encoding:'utf8'});fs.writeFileSync(out+'/'+n+'.log',(p.stdout||'')+'\n'+(p.stderr||''),{flag:'wx'});if(p.status!==0)throw Error(n+' failed '+p.status);console.log(n,'PASS');}
