import test from 'node:test';import assert from 'node:assert/strict';
import {setup,MemoryStorage,application} from './runtime/production/tests/fixtures/setup.ts';
import {Graph} from './runtime/production/src/model/graph.ts';
import {EditorApplication} from './runtime/production/src/application/editor.ts';
import {imageKind,esProfile} from './runtime/production/src/modules/image.ts';
import {nodeRef} from './runtime/production/src/modules/nodes.ts';
import {writeDocument} from './runtime/production/src/persistence/codec.ts';
import {asNetwork,resolveOccurrence} from './runtime/production/src/sdk/networks.ts';
function one(fn:any){const original=Graph.prototype.capture;let n=0;Graph.prototype.capture=function(){n++;return original.call(this);};try{const value=fn();assert.equal(n,1);return value;}finally{Graph.prototype.capture=original;}}
function frozen(v:any){if(v&&typeof v==='object'){assert.ok(Object.isFrozen(v));for(const x of Object.values(v))frozen(x);}}
test('Reviewer: three shared occurrences including nested ancestry use fresh coherent immutable reads; navigation and load revoke only applicable handles',()=>{const s=setup();let child='',second='',parent='',inner='',leaf='',defId='';s.graph.change('Fixture',(d:any)=>{child=d.createSubgraph(s.network,'Child');parent=d.createSubgraph(s.network,'Parent');});let doc=s.graph.capture().document;const cr=doc.graph.resources.find((r:any)=>r.id===(doc.graph.stages.find((t:any)=>t.network.id===s.network)!.network.nodes.find((n:any)=>n.id===child)!.state as any).definition)!;defId=cr.id;const cn=asNetwork(cr,s.fixed)!;const pr=doc.graph.resources.find((r:any)=>r.id===(doc.graph.stages.find((t:any)=>t.network.id===s.network)!.network.nodes.find((n:any)=>n.id===parent)!.state as any).definition)!;const pn=asNetwork(pr,s.fixed)!;s.graph.change('Shared fixture',(d:any)=>{second=d.addReferenceNode(s.network,'call',defId);inner=d.addReferenceNode(pn.network.id,'call',defId);leaf=d.add(cn.network.id,nodeRef('float'),[12,34]);});const app=new EditorApplication(s.definitions,s.identity,imageKind.ref,esProfile,new MemoryStorage(),{download:async()=>{}});assert.equal(app.openText(writeDocument(s.graph.capture().document)).status,'editable');const a=app.context(),b=app.context(),c=app.context();a.enter(child);b.enter(second);c.enter(parent);c.enter(inner);const fields=[a,b,c].map(x=>app.parameter(x,leaf,'value',x.capture().scope));let notices=0;const unsubs=fields.map(f=>f.subscribe(()=>notices++));const initial=app.snapshot,before=[a,b,c].map(x=>one(()=>x.capture()));assert.notDeepEqual(before[0].scope.networkPath,before[1].scope.networkPath);assert.equal(before[2].scope.networkPath.length,2);for(const snap of before){frozen(snap);assert.deepEqual(snap.network,resolveOccurrence(snap.graph.document,s.fixed,snap.scope.stageId,snap.scope.networkPath).network);assert.throws(()=>snap.network.nodes.push({}));}const beforeBytes=JSON.stringify(before);for(let i=0;i<3;i++){const f=one(()=>fields[i].capture());frozen(f);assert.equal(f.projection.value,0.25);assert.throws(()=>{f.projection.value=8;});one(()=>[a,b,c][i].network());}assert.deepEqual(app.snapshot,initial);assert.equal(notices,0);const token=fields[0].capture().editToken;fields[0].commit(0.625,token);for(const f of fields)assert.equal(one(()=>f.capture()).projection.value,0.625);assert.equal(JSON.stringify(before),beforeBytes);assert.ok(notices>0);assert.throws(()=>fields[1].commit(0.4,token),/STALE_EDIT/);c.navigate(c.capture().scope.stageId,[]);assert.throws(()=>fields[2].capture(),/TARGET_EXPIRED|STALE_SCOPE/);assert.equal(fields[0].capture().projection.value,0.625);const latest=writeDocument(app.snapshot.document);app.openText(latest);for(const f of fields)assert.throws(()=>f.capture(),/TARGET_EXPIRED|CONTEXT_DISPOSED|STALE_SCOPE/);for(const off of unsubs)off();});
test('Reviewer: readonly, invalid gesture batch, cancel, single committed Undo and equal-value commit retain tokens/notifications without capture writes',()=>{const s=application(),id=s.add('float'),field=s.app.parameter(s.context,id,'value',s.context.capture().scope);let notices=0;const off=field.subscribe(()=>notices++);const token=field.capture().editToken,initial=s.app.snapshot.document;for(let i=0;i<8;i++)one(()=>field.capture());assert.equal(notices,0);field.commit(0.25,token);assert.equal(field.capture().editToken,token);assert.deepEqual(s.app.snapshot.document,initial);s.app.setReadonly(true);assert.equal(field.capture().writable,false);assert.throws(()=>field.commit(0.4,token),/FIELD_READONLY/);s.app.setReadonly(false);const origin={panelId:'test',typeId:'test'},start=()=>s.app.beginGesture(origin,s.target(),{commandId:'grape.node.move',args:{ids:[id]}});const g=start();assert.equal(field.capture().writable,false);const pre=s.app.snapshot;assert.throws(()=>g.update({positions:{[id]:[NaN,2]}}));assert.deepEqual(s.app.snapshot,pre);g.update({positions:{[id]:[30,45]}});assert.equal(field.capture().editToken,token);g.cancel();assert.deepEqual(s.app.snapshot.document,initial);assert.equal(field.capture().writable,true);const h=start();h.update({positions:{[id]:[30,45]}});h.update({positions:{[id]:[80,65]}});h.commit();const moved=s.app.snapshot.document;s.app.execute(origin,s.target(),{commandId:'grape.undo',args:{}});assert.deepEqual(s.app.snapshot.document,initial);s.app.execute(origin,s.target(),{commandId:'grape.redo',args:{}});assert.deepEqual(s.app.snapshot.document,moved);assert.ok(notices>0);off();field.dispose();assert.throws(()=>field.capture(),/TARGET_EXPIRED/);});
