const fs=require('fs'),cp=require('child_process'),path=require('path'),crypto=require('crypto');
const root=process.cwd(),out=root+'/.verification/s05-drag-performance-review-01',source='C:/Users/user/source/Grape',runtime=out+'/runtime';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');const read=p=>JSON.parse(fs.readFileSync(p));const write=(n,v)=>fs.writeFileSync(out+'/'+n,JSON.stringify(v,null,2)+'\n',{flag:'wx'});
const packetPath='production/evidence/coordinator/s05/review-06/reviewer-packet-01.json',packet=read(source+'/'+packetPath);
const packetRefs=[...packet.inputRefs,...packet.contractRefs,...packet.changedPaths,packet.build.archive];
function verify(rows,base){const errors=[];for(const r of rows){try{const b=fs.readFileSync(base+'/'+r.file);if(b.length!==r.bytes||hash(b)!==r.sha256)errors.push({file:r.file,expected:r,actual:{bytes:b.length,sha256:hash(b)}});}catch(e){errors.push({file:r.file,error:e.code});}}return {count:rows.length,errors};}
const refs=verify(packetRefs,root);const manifests={};for(const name of ['source-config-manifest','evidence-manifest','protected-identities']){const m=read(root+'/production/evidence/s05/drag-performance-repair-01/'+name+'-01.json');manifests[name]=verify(m.files,root);}
write('input-integrity-01.json',{packet:{file:packetPath,sha256:hash(fs.readFileSync(source+'/'+packetPath)),bytes:fs.statSync(source+'/'+packetPath).size},refs,manifests});
const git=(args)=>cp.execFileSync('git',args,{cwd:root,encoding:'utf8',maxBuffer:4e6}).trim();
write('git-binding-01.json',{head:git(['rev-parse','HEAD']),status:git(['status','--porcelain']),implementationI:packet.implementationI,submittedR:packet.submittedHeadR,iToR:git(['diff','--name-status',packet.implementationI,packet.submittedHeadR]),r5ToI:git(['diff','--name-status',packet.priorR,packet.implementationI]),productDiff:git(['diff',packet.priorR,packet.implementationI,'--','production/src','production/tests','production/apps','production/package.json','production/package-lock.json']),ancestorChecks:[packet.acceptedMain,packet.priorR,packet.implementationI].map(ref=>({ref,status:cp.spawnSync('git',['merge-base','--is-ancestor',ref,packet.submittedHeadR],{cwd:root}).status}))});
if(refs.errors.length||Object.values(manifests).some(v=>v.errors.length))console.log('INPUT_MISMATCHES '+JSON.stringify({refs,manifests}));
fs.mkdirSync(runtime,{recursive:true});const archive=out+'/exact-r.tar';cp.execFileSync('git',['archive','--format=tar','--output='+archive,packet.submittedHeadR],{cwd:root});cp.execFileSync('tar',['-xf',archive,'-C',runtime]);
fs.cpSync(source+'/production/node_modules',runtime+'/production/node_modules',{recursive:true});
const deps=read(runtime+'/production/node_modules/.package-lock.json'),lock=read(runtime+'/production/package-lock.json'),differences=[];for(const [p,v]of Object.entries(deps.packages)){const expected=lock.packages[p];if(!expected||v.version!==expected.version||v.integrity!==expected.integrity)differences.push({p,actual:v,expected});}const rows=[];function walk(dir,base){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=dir+'/'+e.name;if(e.isDirectory())walk(p,base);else if(e.isFile()){const b=fs.readFileSync(p);rows.push({file:p.slice(base.length+1),bytes:b.length,sha256:hash(b)});}}}walk(runtime+'/production/node_modules',runtime+'/production/node_modules');
write('dependency-identity-01.json',{method:'Copied production/node_modules bytes from read-only original; every copied regular file hashed; hidden lock version/integrity compared to candidate lock.',node:process.version,lockSha256:hash(fs.readFileSync(runtime+'/production/package-lock.json')),packageCount:Object.keys(deps.packages).length,differences,files:rows});
fs.writeFileSync(out+'/browser.config.mjs',`export default {testDir:${JSON.stringify(runtime+'/production/tests/browser')},fullyParallel:false,workers:1,timeout:60000,retries:0,reporter:[['list'],['json',{outputFile:process.env.GRAPE_EVIDENCE_DIR+'/browser-results.json'}]],use:{baseURL:'http://127.0.0.1:4186',viewport:{width:1440,height:1000},trace:'retain-on-failure',screenshot:'only-on-failure',launchOptions:{args:['--enable-logging=stderr']}},webServer:{command:'node node_modules/vite/bin/vite.js --host 127.0.0.1 --port 4186 --strictPort',cwd:${JSON.stringify(runtime+'/production')},url:'http://127.0.0.1:4186',reuseExistingServer:false},projects:[{name:'chromium',use:{browserName:'chromium'}}]};\n`,{flag:'wx'});
console.log(JSON.stringify({out,runtime,refs:refs.count,manifestCounts:Object.fromEntries(Object.entries(manifests).map(([k,v])=>[k,{count:v.count,mismatches:v.errors.length}])),dependencyFiles:rows.length,dependencyDifferences:differences.length}));

