import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {chromium,expect} from '../../production/node_modules/@playwright/test/index.mjs';import {createServer} from '../../production/node_modules/vite/dist/node/index.js';
const root=process.cwd(),out=path.resolve('.verification/s06-debug-hover-review-02/additional-public-01');fs.mkdirSync(out,{recursive:true});const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),save=(n,v)=>fs.writeFileSync(path.join(out,n+'.json'),JSON.stringify(v,null,2));const result={started:new Date().toISOString(),author:'/root/s06_ui_repair_review_02',cases:[],failures:[]};
const manifest=JSON.parse(fs.readFileSync('production/evidence/s06/debug-hover-repair-01/build-01/build-manifest.json'));const files=new Map(manifest.files.map(r=>{const b=fs.readFileSync(path.resolve('.verification/s06-debug-hover-review-02/archive-01/scratch',r.file));assert.equal(sha(b),r.sha256);return['/'+r.file,b]}));files.set('/',files.get('/index.html'));const wrapper='<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Grape S06 · 本機預覽</title><style>html,body{height:100%;margin:0;background:#14141c}iframe{display:block;width:100%;height:100%;border:0}</style><iframe src="/" title="Grape S06 工作區"></iframe></html>';files.set('/review.html',Buffer.from(wrapper));result.wrapperSha256=sha(Buffer.from(wrapper));
const staticServer=http.createServer((req,res)=>{const b=files.get(req.url);res.writeHead(b?200:404,{'Content-Type':req.url.endsWith('.js')?'text/javascript':req.url.endsWith('.css')?'text/css':'text/html','Cache-Control':'no-store'});res.end(b)});await new Promise(r=>staticServer.listen(0,'127.0.0.1',r));const source=await createServer({root:path.join(root,'production'),server:{host:'127.0.0.1',port:0,watch:{ignored:['**/evidence/**']}},logLevel:'warn'});await source.listen();const origins={archive:'http://127.0.0.1:'+staticServer.address().port,source:source.resolvedUrls.local[0].replace(/\/$/,'')};result.origins=origins;const browser=await chromium.launch();result.browser=browser.version();result.node=process.version;
const button=(app,name)=>app.getByRole('button',{name,exact:true});
async function action(app,name){let a=app.getByRole('menuitem',{name,exact:true,includeHidden:true});if(await a.count()){await button(app,'Project actions').click();await a.click()}else await button(app,name).click()}
async function exp(page,app,name){const [d]=await Promise.all([page.waitForEvent('download'),action(app,'Export JSON')]);const file=await d.path();const b=fs.readFileSync(file);fs.writeFileSync(path.join(out,name+'.grape.json'),b);return JSON.parse(b)}
async function enable(page,app){await button(app,'Experimental features').click();await app.getByRole('checkbox',{name:'Show object information instead of normal hover hints'}).check();await page.keyboard.press('Escape')}
async function focus(page,loc){for(let i=0;i<180;i++){if(await loc.evaluate(e=>e===document.activeElement))return i;await page.keyboard.press('Shift+Tab')}throw Error('Natural focus not reached')}
async function center(loc){const b=await loc.boundingBox();assert(b,'visible target has bounds');return{x:b.x+b.width/2,y:b.y+b.height/2}}
async function trace(app){await app.evaluate(()=>{window.__audit=[];for(const type of ['pointerover','pointermove','pointerdown','pointerup','click','keydown','focusin'])document.addEventListener(type,e=>window.__audit.push({type,trusted:e.isTrusted,x:e.clientX,y:e.clientY,key:e.key,time:e.timeStamp,target:e.target.tagName,label:e.target.getAttribute?.('aria-label'),summary:document.querySelector('.hover-summary')?.textContent}),true)})}
async function route(page,app,target,expected,name,slow=false){const start=await center(target);await page.mouse.move(start.x,start.y);await page.waitForTimeout(220);const before=await app.locator('.hover-summary').innerText();assert(before.includes(expected),before);const to=await center(button(app,'Read object details'));if(slow){for(let n=1;n<=80;n++){await page.mouse.move(start.x+(to.x-start.x)*n/80,start.y+(to.y-start.y)*n/80);await page.waitForTimeout(35)}}else await page.mouse.move(to.x,to.y,{steps:80});await page.waitForTimeout(300);await page.mouse.down();await page.mouse.up();const dialog=app.getByRole('dialog',{name:'Object information',exact:true});await expect(dialog).toBeVisible();const text=await dialog.getByRole('region').innerText();assert(text.startsWith(expected+':'),text);await page.screenshot({path:path.join(out,name+'.png')});await page.keyboard.press('Escape');return{before,text,slow,haltAtActionMs:300,steps:80,from:start,to}}
async function load(page,app,file){const [chooser]=await Promise.all([page.waitForEvent('filechooser'),action(app,'Open file')]);await chooser.setFiles(file);await button(app,'Open in new session').click();await expect(app.locator('#recovery')).not.toBeVisible()}
try{
 for(const wrapped of [false,true])for(const width of [1440,1920]){const name=(wrapped?'wrapped':'direct')+'-'+width,context=await browser.newContext({viewport:{width,height:1000}}),page=await context.newPage();page.on('dialog',d=>d.accept());await context.tracing.start({screenshots:true,snapshots:true});await page.goto(origins.archive+(wrapped?'/review.html':'/'));const app=wrapped?await(await page.locator('iframe').elementHandle()).contentFrame():page;await trace(app);const r={name,routes:[],lifetime:[]};try{
await load(page,app,path.resolve('production/evidence/s06/debug-hover-repair-01/samples/workspace-color.grape.json'));await expect(app.locator('.node')).toHaveCount(2);const node=app.locator('.node').filter({has:app.getByRole('heading',{name:'Color RGBA',exact:true})});await node.getByRole('heading').click();const nodeId=await node.getAttribute('data-node');const docBefore=await exp(page,app,name+'-sample-before'),selection=await app.locator('.canvas').getAttribute('data-selection');await enable(page,app);
for(const [kind,target]of [['Node',node.getByRole('heading')],['Port',node.locator('[data-port]').first()],['Parameter Widget',app.getByRole('textbox',{name:'R',exact:true})]]){const row=await route(page,app,target,kind,name+'-'+kind.replaceAll(' ','-'),true);assert(row.text.includes(nodeId),row.text);r.routes.push(row)}assert.equal(await app.locator('.canvas').getAttribute('data-selection'),selection);assert.deepEqual(await exp(page,app,name+'-sample-after'),docBefore);
await button(app,'Generate GLSL').click();await button(app,'Shader output').click();await expect(app.locator('#code')).toContainText('Generated successfully');r.generated=await app.getByLabel('Generated GLSL',{exact:true}).innerText();assert(r.generated.includes('#version 300 es'));fs.writeFileSync(path.join(out,name+'-generated.glsl'),r.generated);await page.keyboard.press('Escape');await button(app,'Save').click();await expect(app.locator('#save-state')).toHaveText('Saved');await action(app,'New document');await action(app,'Open saved');await app.locator('#saved-list button').click();await expect(app.locator('.node')).toHaveCount(2);assert.deepEqual(await exp(page,app,name+'-reopened'),docBefore);r.roundtrip='same export after acknowledged Save and Open saved';
// A real delete invalidates current detail target. Then the same persistent IDs are reopened with a fresh lifetime.
await app.getByRole('heading',{name:'Color RGBA',exact:true}).click();const target=app.getByRole('heading',{name:'Color RGBA',exact:true});await target.hover();await page.waitForTimeout(220);const oldElement=await target.elementHandle();await button(app,'Delete selected').click();await expect(app.locator('.node')).toHaveCount(1);assert.equal(await oldElement.evaluate(e=>e.isConnected),false);r.lifetime.push({boundary:'delete',oldConnected:false,detailsOpen:await app.getByRole('dialog',{name:'Object information'}).isVisible()});
await button(app,'Generate GLSL').click();await button(app,'Shader output').click();const locate=app.locator('#code').getByRole('button',{name:'Locate node',exact:true}).first();await locate.click();const located=await app.locator('.canvas').getAttribute('data-selection');assert(located.includes('c1bc97af-72d8-483a-9a70-15c6d67fb67b'));await locate.evaluate(e=>window.__oldLocate=e);await page.keyboard.press('Escape');
await load(page,app,path.join(out,name+'-sample-before.grape.json'));await expect(app.locator('.node')).toHaveCount(2);const stale=await app.evaluate(()=>{const b=window.__oldLocate;const before=document.querySelector('.canvas').getAttribute('data-selection');b.click();return{connected:b.isConnected,before,after:document.querySelector('.canvas').getAttribute('data-selection')}});assert.equal(stale.connected,false);assert.equal(stale.before,stale.after);r.lifetime.push({boundary:'same-ID document replacement',...stale,method:'retained DOM callback invoked synthetically after trusted file-open replacement'});await app.getByRole('heading',{name:'Color RGBA',exact:true}).hover();await page.waitForTimeout(220);await route(page,app,app.getByRole('heading',{name:'Color RGBA',exact:true}),'Node',name+'-fresh-after-reopen');r.status='PASS';await page.screenshot({path:path.join(out,name+'-final.png')});
}catch(e){r.status='FAIL';r.error=e.stack;result.failures.push(name);await page.screenshot({path:path.join(out,name+'-failure.png')})}finally{save(name+'-events',await app.evaluate(()=>window.__audit));save(name,r);result.cases.push(r);await context.tracing.stop({path:path.join(out,name+'-trace.zip')});await context.close()}}
}finally{await browser.close();await source.close();await new Promise(r=>staticServer.close(r));result.ownedListenersClosed=true;result.completed=new Date().toISOString();save('result',result);console.log(JSON.stringify({cases:result.cases.map(r=>({name:r.name,status:r.status,error:r.error})),failures:result.failures},null,2))}
