import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {chromium,expect} from '../../production/node_modules/@playwright/test/index.mjs';import {createServer} from '../../production/node_modules/vite/dist/node/index.js';
const root=process.cwd(),out=path.resolve('.verification/s06-debug-hover-review-02/independent-probes-02');fs.mkdirSync(out,{recursive:true});const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),save=(n,v)=>fs.writeFileSync(path.join(out,n+'.json'),JSON.stringify(v,null,2));const result={started:new Date().toISOString(),author:'/root/s06_ui_repair_review_02',cases:[],failures:[]};
const manifest=JSON.parse(fs.readFileSync('production/evidence/s06/debug-hover-repair-01/build-01/build-manifest.json'));const files=new Map(manifest.files.map(r=>{const b=fs.readFileSync(path.resolve('.verification/s06-debug-hover-review-02/archive-01/scratch',r.file));assert.equal(sha(b),r.sha256);return['/'+r.file,b]}));files.set('/',files.get('/index.html'));const wrapper='<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Grape S06 · 本機預覽</title><style>html,body{height:100%;margin:0;background:#14141c}iframe{display:block;width:100%;height:100%;border:0}</style><iframe src="/" title="Grape S06 工作區"></iframe></html>';files.set('/review.html',Buffer.from(wrapper));result.wrapperSha256=sha(Buffer.from(wrapper));
const staticServer=http.createServer((req,res)=>{const b=files.get(req.url);res.writeHead(b?200:404,{'Content-Type':req.url.endsWith('.js')?'text/javascript':req.url.endsWith('.css')?'text/css':'text/html','Cache-Control':'no-store'});res.end(b)});await new Promise(r=>staticServer.listen(0,'127.0.0.1',r));const source=await createServer({root:path.join(root,'production'),server:{host:'127.0.0.1',port:0,watch:{ignored:['**/evidence/**']}},logLevel:'warn'});await source.listen();const origins={archive:'http://127.0.0.1:'+staticServer.address().port,source:source.resolvedUrls.local[0].replace(/\/$/,'')};result.origins=origins;const browser=await chromium.launch();result.browser=browser.version();result.node=process.version;
const button=(app,name)=>app.getByRole('button',{name,exact:true});
async function action(app,name){let a=app.getByRole('menuitem',{name,exact:true,includeHidden:true});if(await a.count()){await button(app,'Project actions').click();await a.click()}else await button(app,name).click()}
async function exp(page,app,name){const [d]=await Promise.all([page.waitForEvent('download'),action(app,'Export JSON')]);const file=await d.path();const b=fs.readFileSync(file);fs.writeFileSync(path.join(out,name+'.grape.json'),b);return JSON.parse(b)}
async function enable(page,app){await button(app,'Experimental features').click();await app.getByRole('checkbox',{name:'Show object information instead of normal hover hints'}).check();await page.keyboard.press('Escape')}
async function focus(page,loc){for(let i=0;i<180;i++){if(await loc.evaluate(e=>e===document.activeElement))return i;await page.keyboard.press('Shift+Tab')}throw Error('Natural focus not reached')}
async function center(loc){const b=await loc.boundingBox();assert(b,'visible target has bounds');return{x:b.x+b.width/2,y:b.y+b.height/2}}
async function trace(app){await app.evaluate(()=>{window.__audit=[];for(const type of ['pointerover','pointermove','pointerdown','pointerup','click','keydown','focusin'])document.addEventListener(type,e=>window.__audit.push({type,trusted:e.isTrusted,x:e.clientX,y:e.clientY,key:e.key,time:e.timeStamp,target:e.target.tagName,label:e.target.getAttribute?.('aria-label'),summary:document.querySelector('.hover-summary')?.textContent}),true)})}
async function route(page,app,target,expected,name,slow=false){const start=await center(target);await page.mouse.move(start.x,start.y);await page.waitForTimeout(220);const before=await app.locator('.hover-summary').innerText();assert(before.includes(expected),before);const to=await center(button(app,'Read object details'));if(slow){for(let n=1;n<=80;n++){await page.mouse.move(start.x+(to.x-start.x)*n/80,start.y+(to.y-start.y)*n/80);await page.waitForTimeout(35)}}else await page.mouse.move(to.x,to.y,{steps:80});await page.waitForTimeout(300);await page.mouse.down();await page.mouse.up();const dialog=app.getByRole('dialog',{name:'Object information',exact:true});await expect(dialog).toBeVisible();const text=await dialog.getByRole('region').innerText();assert(text.startsWith(expected+':'),text);await page.screenshot({path:path.join(out,name+'.png')});await page.keyboard.press('Escape');return{before,text,slow,haltAtActionMs:300,steps:80,from:start,to}}
try{
 for(const mode of ['source','archive'])for(const width of [1440,1920]){const name=mode+'-'+width,context=await browser.newContext({viewport:{width,height:1000}}),page=await context.newPage();page.on('dialog',d=>d.accept());await context.tracing.start({screenshots:true,snapshots:true});await page.goto(origins[mode]);const app=page;await trace(app);const r={name};try{r.renderer=await page.evaluate(()=>{const c=document.createElement('canvas'),g=c.getContext('webgl2');const e=g.getExtension('WEBGL_debug_renderer_info');return g.getParameter(e.UNMASKED_RENDERER_WEBGL)});const initial=await exp(page,app,name+'-before');const selected=await app.locator('.canvas').getAttribute('data-selection');await enable(page,app);r.originalPointer=await route(page,app,app.getByRole('heading',{name:'Image output',exact:true}),'Node',name+'-original');assert(r.originalPointer.text.includes('Node: Image output'));r.originalPointerSlow=await route(page,app,app.getByRole('heading',{name:'Image output',exact:true}),'Node',name+'-slow',true);
const generate=button(app,'Generate GLSL');r.tabs=await focus(page,generate);const n=await center(app.getByRole('heading',{name:'Image output',exact:true}));await page.mouse.move(n.x,n.y,{steps:30});await page.waitForTimeout(220);await expect(generate).toBeFocused();r.beforeF2=await app.locator('.hover-summary').innerText();await page.keyboard.press('F2');const d=app.getByRole('dialog',{name:'Object information',exact:true});r.focusedText=await d.getByRole('region').innerText();assert(r.focusedText.startsWith('UI control: Generate GLSL'));await page.screenshot({path:path.join(out,name+'-focusA-hoverB.png')});await page.keyboard.press('Escape');await expect(generate).toBeFocused();assert.equal(await app.locator('.canvas').getAttribute('data-selection'),selected);assert.deepEqual(await exp(page,app,name+'-after'),initial);r.status='PASS'}catch(e){r.status='FAIL';r.error=e.stack;result.failures.push(r.name);await page.screenshot({path:path.join(out,name+'-failure.png')})}finally{save(name+'-events',await app.evaluate(()=>window.__audit));save(name,r);result.cases.push(r);await context.tracing.stop({path:path.join(out,name+'-trace.zip')});await context.close()}}
 for(const wrapped of [false,true])for(const [width,height]of [[620,380],[620,1000],[1440,1000],[1920,1000]]){const name=(wrapped?'wrapped':'direct')+'-'+width+'-'+height,context=await browser.newContext({viewport:{width,height}}),page=await context.newPage();page.on('dialog',d=>d.accept());await context.tracing.start({screenshots:true,snapshots:true});await page.goto(origins.archive+(wrapped?'/review.html':'/'));const app=wrapped?await(await page.locator('iframe').elementHandle()).contentFrame():page;const r={name,surfaces:[]};try{if(wrapped){assert.equal((await page.locator('iframe').boundingBox()).y,0);assert.equal(await page.locator('header').count(),0)}await expect(app.locator('.build-identity')).toHaveText(manifest.buildId);await expect(app.locator('#code')).not.toBeVisible();r.canvas=await app.locator('.canvas').boundingBox();await page.screenshot({path:path.join(out,name+'-closed.png')});for(const n of ['Project actions','Shader output','Hints','Experimental features']){await button(app,n).click();const popup=app.locator('.floating-surface[open]').last();const b=await popup.boundingBox();assert(b.x>=0&&b.y>=0&&b.x+b.width<=width&&b.y+b.height<=height,JSON.stringify(b));r.surfaces.push({name:n,b});await page.screenshot({path:path.join(out,name+'-'+n.replaceAll(' ','-')+'.png')});await page.keyboard.press('Escape');await expect(button(app,n)).toBeFocused()}await button(app,'本輪更新').click();await expect(app.getByRole('dialog',{name:'本輪更新',exact:true})).toContainText(manifest.implementationI);await page.keyboard.press('Escape');r.status='PASS'}catch(e){r.status='FAIL';r.error=e.stack;result.failures.push(r.name);await page.screenshot({path:path.join(out,name+'-failure.png')})}finally{save(name,r);result.cases.push(r);await context.tracing.stop({path:path.join(out,name+'-trace.zip')});await context.close()}}
}finally{await browser.close();await source.close();await new Promise(r=>staticServer.close(r));result.ownedListenersClosed=true;result.completed=new Date().toISOString();save('result',result);console.log(JSON.stringify(result,null,2))}

