import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const s=path.dirname(fileURLToPath(import.meta.url)), root=path.resolve(s,'../..'), prod=path.join(s,'source/production');
fs.mkdirSync(path.join(s,'tmp'),{recursive:true});
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const records=[];
const run=(id,args,cwd=root)=>{const start=new Date().toISOString();const r=spawnSync(process.execPath,args,{cwd,encoding:'utf8',env:{...process.env,TEMP:path.join(s,'tmp'),TMP:path.join(s,'tmp')},maxBuffer:64*1024*1024,timeout:300000});fs.writeFileSync(path.join(s,id+'.log'),(r.stdout||'')+(r.stderr||'')+(r.error?String(r.error):''));const rec={id,args,cwd,start,exitCode:r.status,signal:r.signal};records.push(rec); console.log(JSON.stringify(rec));fs.writeFileSync(path.join(s,'commands.json'),JSON.stringify(records,null,2));return r;};
const packetPath='C:/Users/user/source/Grape/production/evidence/coordinator/continuous/20261005-01/s06-reviewer-packet-01.json';
const packet=JSON.parse(fs.readFileSync(packetPath));
const checks=[]; const verify=(ref,base=root)=>{const p=path.resolve(base,ref.file);const b=fs.readFileSync(p);const got={file:ref.file,bytes:b.length,sha256:hash(b)};checks.push({...got,pass:b.length===ref.bytes&&got.sha256===ref.sha256});};
verify({file:packetPath,bytes:fs.statSync(packetPath).size,sha256:'f84f04ebb487624429de302621a09550f2c2d59134c2f702a4ba7b7794ff9efa'});
verify(packet.authorizationRef,'C:/Users/user/source/Grape');packet.inputRefs.forEach(r=>verify(r));
const manifest=JSON.parse(fs.readFileSync(path.join(root,'production/evidence/s06/owner-corrections-01/build-01/source-config-manifest.json')));manifest.files.forEach(r=>verify(r));
const refs=new Map(); const visit=x=>{if(!x||typeof x!=='object')return;if(typeof x.file==='string'&&Number.isInteger(x.bytes)&&typeof x.sha256==='string'&&!path.isAbsolute(x.file)&&!refs.has(x.file)){refs.set(x.file,x);if(fs.existsSync(path.join(root,x.file)))verify(x);else checks.push({file:x.file,pass:false,error:'missing'});}Object.values(x).forEach(v=>Array.isArray(v)?v.forEach(visit):visit(v));};
for(const p of ['production/evidence/s06/owner-corrections-01/submission-01.json','production/evidence/s06/owner-corrections-01/requirement-mapping-01.json'])visit(JSON.parse(fs.readFileSync(path.join(root,p))));
const copied=manifest.files.filter(r=>fs.existsSync(path.join(s,'source',r.file))).map(r=>({file:r.file,pass:hash(fs.readFileSync(path.join(s,'source',r.file)))===r.sha256}));
fs.writeFileSync(path.join(s,'identity.json'),JSON.stringify({packet,checks,copied,failures:checks.filter(x=>!x.pass)},null,2));console.log('hashes',checks.length,'failures',checks.filter(x=>!x.pass).length,'copy',copied.length,copied.filter(x=>!x.pass).length);
run('root-integrity',['tools/verify-bootstrap.mjs']);run('root-state',['handoff/tools/check-implementation-state.mjs','--current']);run('root-tests',['--test','tools/verify-bootstrap.test.mjs']);
run('typecheck',['node_modules/typescript/bin/tsc','--noEmit'],prod);
run('module-pins',['tools/module-pins.mjs'],prod);run('boundaries',['tools/boundaries.mjs'],prod);
const tests=['tests/unit','tests/conformance'].flatMap(d=>fs.readdirSync(path.join(prod,d)).filter(x=>x.endsWith('.test.ts')).map(x=>d+'/'+x));run('unit-conformance',['--experimental-transform-types','--test','--test-isolation=none',...tests],prod);
run('build',['tools/build-candidate.mjs',path.join(s,'rebuilt'),path.join(root,'production/evidence/s06/owner-corrections-01/build-01/build-metadata.json')],prod);
