const fs=require('fs'),path=require('path'),crypto=require('crypto'),cp=require('child_process');
const root='C:/Users/user/source/Grape',scratch=__dirname,out=root+'/production/evidence/s05/drag-performance-01';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=n=>JSON.parse(fs.readFileSync(out+'/'+n)),write=(n,x)=>fs.writeFileSync(out+'/'+n,JSON.stringify(x,null,2)+'\n',{flag:'wx'});
const a=read('aggregate-01.json'),get=k=>a.grouped.find(g=>g.key===k),med=x=>[...x].sort((a,b)=>a-b)[Math.floor(x.length/2)];
const records=prefix=>fs.readdirSync(out).filter(f=>f.startsWith(prefix)&&f.endsWith('.json')&&!f.includes('.trace')).map(f=>({file:f,...read(f)}));
const minimal=records('minimal01-'),detail=records('detail01-');
const overhead=['Multiply','Image output'].map(actor=>{const b=get('i4/14/'+actor+'/mounted/off').elapsedMs.p50,c=get('i4/14/'+actor+'/mounted/count').elapsedMs.p50,t=get('i4/14/'+actor+'/mounted/timed').elapsedMs.p50,m=med(minimal.filter(r=>r.actor===actor).map(r=>r.ended-r.started));return{actor,minimalObserverMedianMs:m,globalWrappersInactiveMedianMs:b,countOnlyMedianMs:c,timedMedianMs:t,globalWrapperVsMinimalPercent:(b/m-1)*100,countVsWrappedBaselinePercent:(c/b-1)*100,timedVsWrappedBaselinePercent:(t/b-1)*100};});
write('overhead-and-widget-detail-01.json',{overhead,meaning:'Non-concurrent three-trial medians; ordinary system variation remains. Minimal baseline has RAF/input/longtask observers but no structuredClone/DOM wrappers. Timed trace trial included in three-trial group; count-only run has no tracing.',detail:detail.map(r=>({file:r.file,actor:r.actor,fields:r.fields,stats:r.stats,errors:r.errors})),minimumObserverRuns:minimal.map(r=>({file:r.file,elapsed:r.ended-r.started,frames:r.frames.length,errors:r.errors}))});
const sourceFiles=['src/model/graph.ts','src/application/editor.ts','src/ui/widgets.ts','src/ui/mount.ts','src/ui/workspace.ts','src/sdk/kernel.ts','src/definitions/constant-analysis.ts','src/features/canvas.ts','src/features/inspector.ts'];
const attribution=sourceFiles.map(file=>{const i4=fs.readFileSync(scratch+'/i4-source/'+file),r5=fs.readFileSync(scratch+'/r5-source/'+file);return{file:'production/'+file,i4Sha256:hash(i4),r5Sha256:hash(r5),equal:i4.equals(r5)};});
write('source-attribution-01.json',{sourceRevisions:{i4:'ee1212fdc54359f1ceba4c4b09f6e7cc06cddc41',r5:'bc74bd9aa7f2d357815cd0dfd0afa0b6088eee3a'},files:attribution,instrumentation:JSON.parse(fs.readFileSync(scratch+'/instrumentation-map.json')),detailAdditions:['PresentationSession.refresh label split by view.kind; mounted update timed separately','FieldTarget projection signature equal/changed counters; no return, lifetime, permission or notification change'],absentCondition:'Omit only Inspector workspace.open in disposable build. This disposes/avoids FieldTargets and widget presentations, not CSS hiding. Sidebar geometry remains unchanged.'});
const harnessFiles=fs.readdirSync(scratch).filter(f=>f.endsWith('.cjs')||f==='instrumentation-map.json');fs.mkdirSync(out+'/harness');for(const f of harnessFiles)fs.copyFileSync(scratch+'/'+f,out+'/harness/'+f,fs.constants.COPYFILE_EXCL);
const copyFiles=[];for(const variant of ['i4-source','r5-source','i4-instrumented-02','r5-instrumented-02','i4-instrumented-03']){
 for(const file of [...sourceFiles,'apps/web/main.ts','tsconfig.json','index.html']){const p=scratch+'/'+variant+'/'+file;if(!fs.existsSync(p))continue;const b=fs.readFileSync(p);const dest='diagnostic-copies/'+variant+'/'+file;fs.mkdirSync(path.dirname(out+'/'+dest),{recursive:true});fs.writeFileSync(out+'/'+dest,b,{flag:'wx'});copyFiles.push({file:dest,bytes:b.length,sha256:hash(b)});}
 for(const file of fs.readdirSync(scratch+'/'+variant+'/dist',{recursive:true}).filter(f=>fs.statSync(scratch+'/'+variant+'/dist/'+f).isFile())){const b=fs.readFileSync(scratch+'/'+variant+'/dist/'+file);const dest='diagnostic-copies/'+variant+'/dist/'+file.replaceAll('\\','/');fs.mkdirSync(path.dirname(out+'/'+dest),{recursive:true});fs.writeFileSync(out+'/'+dest,b,{flag:'wx'});copyFiles.push({file:dest,bytes:b.length,sha256:hash(b)});}
}
write('diagnostic-copy-manifest-01.json',{purpose:'Disposable source snapshots and instrumented artifacts only. Never product changes or accepted build replacements.',files:copyFiles});
write('setup-observations-01.json',{operations:[{operation:'Preimage integrity',outcome:'First read-only approach used one git show process per tracked path and was cancelled due unnecessary latency before any durable output. Replaced with exact Git blob hash comparison against clean index; no product mutation or tool refusal.'},{operation:'Windows process query',outcome:'Get-CimInstance read denied; no process was changed; owning read-only tool session was cancelled directly.'},{operation:'Disposable reconstruction',outcome:'First instrument anchor assumed CRLF while I4 used LF, and first source build omitted tsconfig. Corrected source-copy setup; both uninstrumented rebuilds then exactly matched archive HTML/JS/CSS. No archive changed.'},{operation:'Browser harness setup1',outcome:'Dialog accessible-name assumption failed; timeout preserved in measurement-error-1791096690268.json.'},{operation:'Browser harness setup2',outcome:'Playwright default dismissed the clean disposable new-document discard confirmation; dialog remained. Timeout retained. Corrected by explicitly accepting this normal public confirmation.'},{operation:'Browser harness setup3',outcome:'First pilot drag completed; second fixture review was still READING_INPUT when checked. Pilot retained separately; final harness waits asynchronous input completion. Not a product admission failure.'},{operation:'Final measurement',outcome:'78 primary + 4 detailed + 6 minimal-baseline cases completed; 1 pilot retained outside comparison. Browser contexts and owned ephemeral server closed. No live service addressed.'}],counters:{actionContinuation:2,actionAttempt:2,transportRetries:0,priorMeasurements:0,repairAttempts:0,primaryExecutionPasses:1,diagnosticHarnessReadinessFailures:3,detailExecutions:1,minimalExecutions:1,independentReviewRoundsForPerformance:0},explanation:'Harness readiness corrections are retained as diagnosis observations, not a product repair, action redispatch or reset of any prior finding group.'});
const pre=read('preimages-01.json'),failures=[];
for(const f of [...pre.tracked,...pre.untracked]){let b;try{b=fs.readFileSync(root+'/'+f.file)}catch(e){failures.push({file:f.file,error:String(e)});continue;}if(b.length!==f.bytes||hash(b)!==f.sha256)failures.push({file:f.file,expected:f.sha256,actual:hash(b)});}
const git=(...args)=>cp.execFileSync('git',args,{cwd:root,encoding:'utf8',maxBuffer:10e6});const head=git('rev-parse','HEAD').trim(),diff=git('diff','--name-only'),index=git('diff','--cached','--name-only');if(head!==pre.head||diff||index||failures.length)throw Error(JSON.stringify({head,diff,index,failures}));
write('preservation-check-01.json',{checkedAt:new Date().toISOString(),head,trackedFiles:pre.tracked.length,untrackedPreimages:pre.untracked.length,allExact:true,trackedDiff:[],indexDiff:[],failures,debugLog:pre.untracked.find(f=>f.file==='production/debug.log'),newFilesOnlyUnderAllowedEvidenceAndIgnoredDiagnosticScratch:true,services:'No live4193/4194/4195 lifecycle or configuration operation issued',noCommit:true});
const report={
 reportId:'S05-DRAG-PERFORMANCE-DIAGNOSIS-02-RESULT-01',actionKey:'yeataro/Grape:S05:drag-performance-diagnosis:676c339:01',findingGroup:'S05-FG-DRAG-PERFORMANCE-01',status:'DIAGNOSIS_COMPLETE_OPTIMIZATION_PROPOSED_NOT_IMPLEMENTED',writer:{displayTitle:'Grape S05 實作與維護',canonicalAgent:'/root/s03_implementer_resume'},createdAt:new Date().toISOString(),
 bindings:{reported4195:{I:'ee1212fdc54359f1ceba4c4b09f6e7cc06cddc41',R:'29695b3c25e2d200856d780b31e20e23f24efb6d',build:'S05-web-ee1212f',archiveSha256:'07edd46c4830fa5113ff096a941693a4349ff2fd66830813b70676850cc358da'},currentFrozen:{I:'8ffbea96bdc76e307d59eaa8514f3c6432a7d34d',R:head,build:'S05-values-8ffbea9',archiveSha256:'808556904749c44c56ee10b2665d20c0cbdf6045b157e5cedb7a0675ef987595'},packetSha256:'b493f72a547f70edb31798db7970de3f86adbc6d1db7fb6bb13b4239f6c5c15a'},
 conclusion:'Reproduced an actor-dependent drag update-rate difference. Selected Multiply with two Inspector fields triggers repeated whole-document detached captures through two notification paths. Removing Inspector FieldTargets in a disposable control removes the actor asymmetry. Synchronous snapshot and projection work dominates these fixtures; shader arithmetic is not implicated. Both I4 and R5 show the same capture counts and source paths.',
 methodology:{primaryDrags:78,detailDrags:4,minimalObserverDrags:6,excludedPilotDrags:1,repeatsPerPrimaryCell:3,graphSizes:[{nodes:4,edges:3,nested:0},{nodes:14,edges:3,nested:0,extra:'ten unconnected Multiply nodes; outside viewport, still in model/DOM'}],viewport:[1440,1000],dpr:1,contexts:1,renderMode:'Headless Chromium151 / ANGLE SwiftShader; Windows11, Ryzen7 9800X3D, no CPU throttle',path:'60 pointer movements: x=x0+60*sin(i*pi/60), y=y0+20*sin(i*pi/60), i1..60; target initial center is identical between actors and Inspector conditions within each build. I4 starts(357,364); R5 starts(357,381) because its catalog action bar is17px taller.',duration:'Same intended1000ms schedule and60 points. Sequential browser input backpressure lengthens actual duration, explicitly recorded; do not claim identical actual duration. First small move stays below4px threshold:59 Graph publications in instrumented cases.',setup:'Public Add/connect/export fixture, then actual Open document file → DOCUMENT_VALID → Open in new session. No model injection or Human browser storage. Compare actor position permutations with identical graph identities/semantics/edge counts.',measurementWindow:'Steady moves only; pointerdown selection excluded, pointerup commit excluded from timers. CDP traces include small setup/release margins. Frame intervals and input intervals reported separately.',instrumentation:'AST try/finally body probes, count-only and timed modes, inactive global wrappers and minimal-observer archived baselines. Inclusive spans overlap; exclusive counters and separate trace categories are provided.',artifactEquivalence:'I4/R5 original JS/CSS served unchanged. Isolated HTML only prefixes asset paths. Both uninstrumented source reconstructions match all3 archive files exactly.'},
 observations:[
 {id:'DP-M01',fact:'4-node I4 baseline Multiply38.24 input requests/s versus ImageOutput58.96; R5 37.90 versus58.86.14-node I4 Multiply28.53 versus33.08; R5 27.85 versus31.33. These are completed input/position-update throughput, not display FPS.',evidence:'aggregate-01.json; raw run04 files'},
 {id:'DP-M02',fact:'For59 publications, mounted Multiply has19544 Graph.capture,708 FieldTarget.capture,236 invalidations,118 Context-origin and118 Application-origin field notifications,236 WidgetSlot.resolve and236 actual widget updates.708 signatures remained unchanged. Two fields × two notification routes × three captures =12 field captures/publication.',evidence:'run04-003-i4-4-Multiply-mounted-timed-0.json; detail01-001-i4-14-Multiply-mounted-timed-0.json'},
 {id:'DP-M03',fact:'ImageOutput has zero fields and8924 Graph captures. Inspector-absent Multiply and ImageOutput both have6446 captures and no FieldTarget notifications. This control removes the entire Inspector, so its improvement includes inspector routing/projection overhead, not only widget DOM.',evidence:'aggregate-01.json'},
 {id:'DP-M04',fact:'I4 14-node mounted Multiply median gesture total1667.8ms/59≈28.27ms each; structuredClone1166.1ms≈69.9% of gesture time. Graph validation42.6ms≈2.6%, constant analysis8.3ms≈0.5%.4-node corresponding gesture839.1ms and clone565.9ms. Constant analysis is nested within validation, never add both totals.',evidence:'aggregate-01.json'},
 {id:'DP-M05',fact:'Workspace.route and Canvas.update each occur118 times for59 Graph publications. Rebuilding Canvas nodes/wires and repeated geometry reads are measured secondary work.14-node trace shows layout71.818ms, style30.570ms, paint19.728ms versus EventDispatch1706.348ms; separate overlapping categories must not be summed as exclusive cost.',evidence:'run04-039-i4-14-Multiply-mounted-timed-0.trace.json; aggregate-01.json'},
 {id:'DP-M06',fact:'Detail case: parameter-widget refresh236 calls takes263.7ms inclusive; actual widget update236 calls takes12.5ms. Most widget refresh cost is projection capture, not drawing numeric text.',evidence:'detail01-001-i4-14-Multiply-mounted-timed-0.json'},
 {id:'DP-M07',fact:'RAF stays near60Hz in4-node cases and roughly58–60Hz in14-node cases while position update throughput drops. The Owner25–30FPS screenshot metric cannot be identified from its crop, so exact equivalence is not claimed.',evidence:'aggregate-01.json; environment-04.json; original Human inputs'},
 {id:'DP-M08',fact:'All instrumented count patterns match across I4 and R5; all9 attributed core/editor/UI files have identical hashes. No evidence attributes this regression to the new fixed-value owner.',evidence:'source-attribution-01.json'}],
 hypothesesAndLimits:['The Human actual graph, operation type, browser origin and FPS overlay implementation are unknown; no Butterfly node is inferred.','The local headless SwiftShader environment reproduces comparative asymmetry, not the exact Human rendering environment or a universal FPS guarantee.','Snapshot allocation is a supported dominant explanation, but no repair was applied or timed. Proposed speedups are not measured.','Only4/14-node,3-edge,zero-nested,one-context fixtures were measured. Large/nested/multicontext performance is not qualified.','Three repeats and non-concurrent matrix order permit thermal/system drift; distributions and trace overhead are retained.','Unchanged projection signatures do not imply writable/busy/token/lifetime notifications may be removed.','Setup harness failures, source-copy preparation corrections and the excluded pilot remain preserved; none invalidate historical independently authored product PASS or qualify a new product build.'],
 boundedProposal:{firstChoice:'Within production/src/application/editor.ts, derive each synchronous EditorContext.capture/network and FieldTarget.capture from one already-detached GraphSnapshot and resolved occurrence. Reuse that call-local network for nodes/links/labels/frames rather than repeatedly invoking context.network()/graph.capture(). Keep output detached/frozen and all current guard/notification semantics. No cross-revision cache required.',whySmallest:'EditorContext.capture currently calls network five times, each network captures Graph twice, on top of its own Graph capture (11 total). Each FieldTarget.capture adds two network calls (15 Graph captures).12 field captures/publication alone account for180 Graph captures. Call-local reuse attacks the measured multiplier without weakening validation or scheduling.',affectedPaths:['production/src/application/editor.ts','focused tests/browser performance harness; eventual source/evidence manifests'],secondaryOnlyIfNeeded:'After first bounded change, rerun the same measurements. Separately consider coalescing redundant projection delivery or per-revision immutable snapshots only if still necessary and with explicit lifecycle/notification counterexamples; not bundled into this diagnosis or a broad cache rewrite.',invariants:['Canonical Graph ownership and all mutation/validation/constant-analysis steps unchanged','One drag operation and commit/cancel/Undo/Redo boundaries unchanged','Capture outputs immutable; no mutable internal document escapes','Scope/load/context/navigation/lifetime/lease/readonly/busy checked as today','Parameter edit tokens, link ABA, input type/owner reconciliation and stale rejection unchanged','No skipping Context/Application notifications solely because numeric value is unchanged','Locale, disposal, widget re-resolution, focused drafts and IME behavior preserved'],requiredRepairEvidence:['Exact new I/R and independent targeted review after source repair','Re-run same immutable fixtures/matrix, count reductions and inclusive/self/trace evidence','Focused lifetime/token/ABA/readonly/busy/navigation/Undo/Redo/drag-cancel and graph validation regressions','Affected S02 replacement, S03 nested Inspector, S04 admission and S05 Uniform/function/fixed-value protection checks']},
 overhead,artifactIndex:{primary:'execution-04.json',aggregate:'aggregate-01.json',detail:'execution-detail-01.json',minimal:'execution-minimal-01.json',environment:'environment-04.json',source:'source-attribution-01.json',fixtures:'fixture-identities-01.json',buildEquivalence:'build-equivalence-01.json',setupHistory:'setup-observations-01.json',preservation:'preservation-check-01.json',manifest:'manifest-01.json'},
 counters:{continuation:2,attempt:2,retriesUsed:0,priorMeasurements:0,repairAttempts:0,unsuccessfulReviewRounds:0,legacyGroup:'repairAttempt2 / unsuccessful0 / globalReview4PASS retained',uniformGroup:'initialFAIL1 / repair1 / review2PASS retained'},
 finalState:{HEAD:head,trackedFilesUnchanged:3627,untrackedPreimagesUnchanged:pre.untracked.length,noCommit:true,productOptimizationImplemented:false,noDeployment:true,noStateChange:true,independentPassClaim:false,humanAcceptance:'NOT_GRANTED',S05:'ACTIVE_INCOMPLETE',next:'Coordinator reconciliation then already-authorized bounded optimization; no further generic Human go-ahead needed',writer:'STOP_WRITING'}
};
write('diagnosis-01.json',report);
const list=fs.readdirSync(out,{recursive:true}).filter(f=>fs.statSync(out+'/'+f).isFile()).map(f=>{const file=f.replaceAll('\\','/'),b=fs.readFileSync(out+'/'+f);return{file,bytes:b.length,sha256:hash(b)}});
write('manifest-01.json',{root:'production/evidence/s05/drag-performance-01',head,files:list,excludedSelf:'manifest-01.json',diagnosisSha256:hash(fs.readFileSync(out+'/diagnosis-01.json'))});
console.log(JSON.stringify({head,files:list.length,report:hash(fs.readFileSync(out+'/diagnosis-01.json')),manifest:hash(fs.readFileSync(out+'/manifest-01.json')),preservation:hash(fs.readFileSync(out+'/preservation-check-01.json')),overhead},null,2));
