import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import cp from 'node:child_process';import assert from 'node:assert/strict';
const root=process.cwd(),out=path.join(root,'.verification/s06-workspace-review-03'),R='4d99a749e9b121acd27a959cb528a77eb425dda4',I='a42d4aedd8e33c1fd432c92163db9f9d689e1bcb',prior='8d7dc0a4531fe14f7a490ddf025a47595e97ae1d',primary='C:/Users/user/source/Grape';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),read=f=>JSON.parse(fs.readFileSync(path.join(root,f))),git=(...args)=>cp.execFileSync('git',args,{cwd:root,encoding:'utf8',maxBuffer:50e6}),write=(f,v)=>fs.writeFileSync(path.join(out,f),typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');
const packetBytes=fs.readFileSync(path.join(primary,'production/evidence/coordinator/s06/review-03/reviewer-packet-01.json'));assert.equal(packetBytes.length,12933);assert.equal(sha(packetBytes),'127efc0b7f68ceb250480253700b7ef4879c88b6f5f0656717da2c7f49153061');write('reviewer-packet-01.json',packetBytes.toString());const packet=JSON.parse(packetBytes);
const groups={sourceConfig:read('production/evidence/s06/workspace-repair-02/build-01/source-config-manifest.json').files,currentEvidence:read('production/evidence/s06/workspace-repair-02/evidence-manifest-01.json').files,originalRawReview2:read('production/evidence/s06/review-02/independent-review/supporting-evidence-manifest-01.json').files.map(r=>({...r,file:'production/evidence/s06/review-02/independent-review/'+r.file})),bindings:[packet.submission,...Object.values(packet.bindings),packet.archive,packet.originalReview,packet.originalSupportingManifest,packet.authorizationRef,packet.workflowControl,packet.networkControl]};
const files=[...new Set(Object.values(groups).flat().map(r=>r.file))],b=cp.execFileSync('git',['cat-file','--batch'],{cwd:root,input:files.map(f=>R+':'+f).join('\n')+'\n',maxBuffer:1024e6});let pos=0;const objects=new Map();for(const file of files){const nl=b.indexOf(10,pos),hdr=b.subarray(pos,nl).toString();pos=nl+1;if(hdr.endsWith(' missing')){objects.set(file,{missing:true});continue;}const [object,type,len]=hdr.split(' '),size=Number(len),blob=b.subarray(pos,pos+size);pos+=size+1;objects.set(file,{object,type,bytes:size,sha256:sha(blob)});}
const result={node:process.version,platform:process.platform,head:git('rev-parse','HEAD').trim(),trackedStatus:git('status','--porcelain=v1','--untracked-files=no'),groups:{},ancestry:{},deltas:{}};assert.equal(result.head,R);
for(const [name,rows]of Object.entries(groups)){result.groups[name]={count:rows.length,rows:rows.map(r=>{const object=objects.get(r.file),disk=fs.existsSync(path.join(root,r.file))?fs.readFileSync(path.join(root,r.file)):null;return {...r,gitObject:object,gitMatches:object.bytes===r.bytes&&object.sha256===r.sha256,checkoutMatches:disk?.length===r.bytes&&sha(disk)===r.sha256};})};result.groups[name].allMatched=result.groups[name].rows.every(r=>r.gitMatches&&r.checkoutMatches);}
for(const [name,a,z]of [['baseToI',packet.acceptedMain,I],['priorToI',prior,I],['IToR',I,R]])result.ancestry[name]=cp.spawnSync('git',['merge-base','--is-ancestor',a,z],{cwd:root}).status===0;
const product=['production/src','production/apps','production/tests','production/tools','production/package.json','production/package-lock.json','production/tsconfig.json'];result.deltas.priorToRProduct=git('diff','--name-status',prior,R,'--',...product);result.deltas.IToRProduct=git('diff','--name-status',I,R,'--',...product);result.deltas.frozenAndAccepted=git('diff','--name-status',prior,R,'--','handoff','production/evidence/acceptance');result.deltas.originalReview2=git('diff','--name-status',prior,R,'--','production/evidence/s06/review-02');write('identity-checks.json',result);write('product-delta.patch',git('diff',prior,R,'--',...product));
assert.ok(Object.values(result.groups).every(g=>g.allMatched));
const runtime=path.join(out,'runtime');fs.mkdirSync(runtime,{recursive:true});for(const r of groups.sourceConfig){const dst=path.join(runtime,r.file);fs.mkdirSync(path.dirname(dst),{recursive:true});fs.copyFileSync(path.join(root,r.file),dst);}
for(const folder of ['handoff','tools'])fs.cpSync(path.join(root,folder),path.join(runtime,folder),{recursive:true});for(const file of fs.readdirSync(root)){if(fs.statSync(path.join(root,file)).isFile())fs.copyFileSync(path.join(root,file),path.join(runtime,file));}
const lock=fs.readFileSync(path.join(root,'production/package-lock.json'));assert.equal(sha(lock),sha(fs.readFileSync(path.join(primary,'production/package-lock.json'))));fs.cpSync(path.join(primary,'production/node_modules'),path.join(runtime,'production/node_modules'),{recursive:true});
const pkg=JSON.parse(lock),dep=JSON.parse(fs.readFileSync(path.join(runtime,'production/node_modules/.package-lock.json')));const deps=Object.entries(dep.packages).map(([p,v])=>({path:p,version:v.version,lockVersion:pkg.packages[p]?.version,integrityMatch:v.integrity===pkg.packages[p]?.integrity}));assert.ok(deps.every(d=>d.version===d.lockVersion&&d.integrityMatch));
const fixtures=['production/evidence/s05/drag-performance-01/fixture-14-Multiply.json'];for(const f of fixtures){const dst=path.join(runtime,f);fs.mkdirSync(path.dirname(dst),{recursive:true});fs.copyFileSync(path.join(root,f),dst);}
const legacy=read('production/evidence/coordinator/s06/preparation-01/legacy-reference-manifest-01.json');const legacyRows=legacy.files.map(r=>{const src=path.join(legacy.sourceRoot,r.file),buf=fs.readFileSync(src),dst=path.join(out,'legacy-reference',r.file);assert.equal(buf.length,r.bytes);assert.equal(sha(buf),r.sha256);fs.mkdirSync(path.dirname(dst),{recursive:true});fs.writeFileSync(dst,buf);return {...r,matched:true};});
write('runtime-preparation.json',{runtime,node:process.version,packageLock:{bytes:lock.length,sha256:sha(lock)},deps,legacyRows,sourceConfig:groups.sourceConfig.length,fixtures});console.log(JSON.stringify({groups:Object.fromEntries(Object.entries(result.groups).map(([k,v])=>[k,{count:v.count,allMatched:v.allMatched}])),ancestry:result.ancestry,deltas:result.deltas,runtime,dependencies:deps.length,legacyFiles:legacyRows.length},null,2));
