const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
class El{constructor(id){this.id=id;this.hidden=id==='lk-menu';this.handlers={};this.attrs={};this.style={};this.selected=new Set;this.classList={toggle:(k,v)=>v?this.selected.add(k):this.selected.delete(k),remove:k=>this.selected.delete(k)};}addEventListener(k,f){this.handlers[k]=f;}setAttribute(k,v){this.attrs[k]=v;}getAttribute(k){return this.attrs[k];}focus(){this.focused=true;}fire(k,extra={}){this.handlers[k]?.({currentTarget:this,preventDefault(){},...extra});}}
const names=['lk-menu','lk-menu-toggle','lk-source-arrow','lk-source','lk-peer-one','lk-peer-two','lk-wire-peer','lk-status','lk-choose-one','lk-choose-two','lk-peer-one-arrow','lk-peer-two-arrow','lk-visibility','lk-link-lines','lk-reset','lk-board'];
const ids=Object.fromEntries(names.map(id=>[id,new El(id)]));ids['lk-visibility'].attrs['aria-pressed']='true';
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'parts/links.js'),'utf8'),{document:{getElementById:id=>{assert(ids[id],id);return ids[id];}}});
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}function selected(id){return ids[id].selected.has('lk-selected');}
test('Source arrow includes exactly two direct Link peers, excludes ordinary Wire',()=>{ids['lk-source-arrow'].fire('click');assert(selected('lk-peer-one'));assert(selected('lk-peer-two'));assert(!selected('lk-wire-peer'));assert(!selected('lk-source'));});
test('Input arrow selects only the source',()=>{ids['lk-peer-two-arrow'].fire('click');assert(selected('lk-source'));assert(!selected('lk-peer-one'));assert(!selected('lk-peer-two'));});
test('Hidden lines retain functioning peer navigation',()=>{ids['lk-visibility'].fire('click');assert.equal(ids['lk-link-lines'].style.display,'none');ids['lk-source-arrow'].fire('click');assert(selected('lk-peer-two'));assert(!selected('lk-wire-peer'));});
test('Right-click menu resolves a single peer',()=>{ids['lk-source-arrow'].fire('contextmenu');assert(!ids['lk-menu'].hidden);ids['lk-choose-one'].fire('click');assert(selected('lk-peer-one'));assert(!selected('lk-peer-two'));assert(ids['lk-menu'].hidden);});
test('Explicit menu entrance and Escape restore arrow focus',()=>{ids['lk-menu-toggle'].fire('click');assert(!ids['lk-menu'].hidden);ids['lk-board'].fire('keydown',{key:'Escape'});assert(ids['lk-menu'].hidden);assert(ids['lk-source-arrow'].focused);});
test('Reset clears selection and restores visible lines',()=>{ids['lk-reset'].fire('click');for(const id of ['lk-source','lk-peer-one','lk-peer-two','lk-wire-peer'])assert(!selected(id));assert.equal(ids['lk-link-lines'].style.display,'');assert.equal(ids['lk-visibility'].getAttribute('aria-pressed'),'true');});
console.log(JSON.stringify({status:'PASS',checks:count,scope:'Offline diagram DOM doubles, not product navigation/runtime'}));
