/* Local review behavior only; no product state, network, persistence or Host. */
(() => {
  const board=document.getElementById('layout-board'), frame=document.getElementById('layout-frame');
  function fit(){const full=frame.classList.contains('full-scale');const s=full?1:Math.min(1,frame.clientWidth/1360);board.style.transform=`scale(${s})`;frame.style.height=`${780*s}px`;}
  new ResizeObserver(fit).observe(frame);fit();
  const descriptions={default:'完整工作區：依 Legacy 配置重組的 1360 × 780 設計畫板。節點內容是縮減示例；宿主路徑與 Save TD project 是 Legacy 外觀，不表示新產品文件由 TD 持有。',minimal:'Minimal 參考：收合產品標題與兩側欄，Inspector／Preview 浮在 Canvas 內。配置來自既有討論與歷史圖，具體位置是圖稿安排；不是 layout 保存／restore 驗收。',focus:'專注 Canvas 參考：把工作空間留給節點與工具入口。這裡只有本頁構圖切換，不宣稱正式 focus mode 的生命期／保存政策已定案。'};
  document.querySelectorAll('button[data-layout]').forEach(b=>b.addEventListener('click',()=>{board.dataset.layout=b.dataset.layout;document.querySelectorAll('button[data-layout]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.getElementById('layout-description').textContent=descriptions[b.dataset.layout];}));
  document.getElementById('layout-scale').addEventListener('click',e=>{const full=frame.classList.toggle('full-scale');e.currentTarget.setAttribute('aria-pressed',String(full));e.currentTarget.textContent=full?'縮回適合頁寬':'1:1 捲動檢視';fit();});
  const dim=document.getElementById('dynamic-dimension'), feature=document.getElementById('dynamic-feature');
  function updatePorts(){const four=dim.value==='4D',edge=feature.value==='edge';document.querySelectorAll('#dynamic-node [data-dynamic=w-input]').forEach(x=>x.hidden=!four);document.querySelectorAll('#dynamic-node [data-dynamic=color],#dynamic-node [data-dynamic=position]').forEach(x=>x.hidden=edge);document.querySelectorAll('#dynamic-node [data-dynamic=w-output]').forEach(x=>x.hidden=!four||edge);document.getElementById('dynamic-state').textContent=`${dim.value} / ${edge?'Distance to Edge':'F1'}：${edge?'只保留 Distance 輸出':four?'Distance、Color、Position、W':'Distance、Color、Position'}。這是接口視覺示範；未執行 Shader。`;}
  dim.addEventListener('change',updatePorts);feature.addEventListener('change',updatePorts);updatePorts();
  document.getElementById('review-export').addEventListener('click',()=>{const review={schema:'grape-design-atlas-review/1',atlasRevision:'ATLAS-005',reviewedAt:new Date().toISOString(),authority:'Human review notes; not automatic architecture or product acceptance.',items:Array.from(document.querySelectorAll('[data-review-id]')).map(row=>({id:row.dataset.reviewId,disposition:row.querySelector('select').value,note:row.querySelector('textarea').value}))};const blob=new Blob([JSON.stringify(review,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='grape-design-atlas-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.getElementById('review-status').textContent='已觸發審查 JSON 下載。請確認瀏覽器下載結果；這不會改寫產品或重構 Repo。';});
})();
