// Metadata-only finalization: explicit allowlist, preserved raw whitespace, no network.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {execFileSync,spawnSync} from 'node:child_process';
const root='C:/Users/user/source/Grape',out=root+'/production/evidence/s05/review-06',prefix='production/evidence/s05/review-06/',R='6c3a734325d0db2d924356a9614e971d80a966c8',I='aa4c86e20b0b4b54218b9992921578e7f24a28a2';
const sha=b=>createHash('sha256').update(b).digest('hex'),blob=b=>createHash('sha1').update(Buffer.from('blob '+b.length+'\0')).update(b).digest('hex'),git=(...a)=>execFileSync('git',a,{cwd:root,encoding:'utf8',maxBuffer:160e6}),read=f=>JSON.parse(fs.readFileSync(f,'utf8')),write=(n,v)=>fs.writeFileSync(out+'/'+n,JSON.stringify(v,null,2)+'\n',{flag:'wx'}),identity=f=>{const b=fs.readFileSync(root+'/'+f);return{file:f,bytes:b.length,sha256:sha(b)}};
assert.equal(git('rev-parse','HEAD').trim(),R);assert.equal(git('diff','--cached','--name-only').trim(),'');assert.deepEqual(git('diff','--name-only').trim().split('\n'),['implementation-state.json']);
const pre=read(out+'/preimages-01.json'),rel=read(out+'/relocation-01.json'),coord=read(out+'/coordinator-inputs-01.json'),sources=read(root+'/production/evidence/s05/drag-performance-repair-01/source-config-manifest-01.json');
for(const r of [...pre.tracked.filter(x=>x.file!=='implementation-state.json'),...pre.untracked,...sources.files,...coord.files]){const n=identity(r.file);assert.equal(n.sha256,r.sha256,r.file);assert.equal(n.bytes,r.bytes);}
for(const r of rel.files){const n=identity(r.destination);assert.equal(n.sha256,r.sha256,r.destination);assert.equal(n.bytes,r.bytes);}
const state=read(root+'/implementation-state.json'),oldState=JSON.parse(git('show',R+':implementation-state.json'));for(const k of Object.keys(oldState).filter(k=>k!=='decisionReferences'))assert.deepEqual(state[k],oldState[k],k);for(let i=0;i<state.decisionReferences.length;i++){const before=oldState.decisionReferences[i],after=state.decisionReferences[i];for(const k of Object.keys(before))if(k!=='scope'||!['DEC-GRAPE-003','AC-GRAPE-002'].includes(before.id))assert.deepEqual(after[k],before[k]);}
const parent=read(root+'/production/evidence/coordinator/s05/review-06/persistence-parent-result-01.json');assert.equal(identity(parent.intent.file).sha256,parent.intent.sha256);
const checks=read(out+'/checks/results-01.json');assert.ok(checks.results.every(r=>r.exitCode===0));const bootstrap=read(out+'/checks/bootstrap.stdout.txt');assert.equal(bootstrap.status,'PASS');assert.equal(bootstrap.checks,471);
write('preservation-01.json',{reviewedI:I,reviewedR:R,rawObjects:rel.files.length,sourceConfigFiles:sources.files.length,existingTrackedUnchanged:pre.tracked.length-1,existingUntrackedPreimagesUnchanged:pre.untracked.length,coordinatorFiles:coord.files.length,READMEUnchanged:true,allProductSourceTestsToolsConfigDependenciesAndBuildUnchanged:true,implementationBaselineUnchanged:true,buildUnchanged:true,activeSlicesUnchanged:true,acceptedEvidenceAndHistoryUnchanged:true,onlyStateChanges:['DEC-GRAPE-003.scope','AC-GRAPE-002.scope'],networkActions:[],serviceActions:[],productActions:[],verdict:'BLOCKED',classification:'WF_PERMISSION',technicalPASS:false,acceptance:'NOT_GRANTED',counters:{repairAttempt:1,unsuccessfulTechnicalReviewRounds:0,globalReviewSequence:6},status:'PRESERVATION_VERIFIED'});
const walk=dir=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(dir+'/'+e.name):[dir+'/'+e.name]);
const allowed=f=>f==='implementation-state.json'||f.startsWith(prefix)||coord.files.some(r=>r.file===f);
const initial=['implementation-state.json',...coord.files.map(r=>r.file),...walk(out).map(f=>f.slice(root.length+1))];assert.equal(new Set(initial).size,initial.length);assert.ok(initial.every(allowed));
// Initial list does not contain its own list file; explicit additional staging follows below.
fs.writeFileSync(out+'/stage-initial.paths',initial.join('\n')+'\n',{flag:'wx'});
git('-c','core.autocrlf=false','add','-f','--pathspec-from-file='+out+'/stage-initial.paths');assert.deepEqual(git('diff','--cached','--name-only','-z').split('\0').filter(Boolean).sort(),[...initial].sort());
const raw=spawnSync('git',['diff','--cached','--check'],{cwd:root,encoding:'utf8',maxBuffer:160e6});fs.writeFileSync(out+'/checks/raw-staged-diff-check.stdout.txt',raw.stdout||'',{flag:'wx'});fs.writeFileSync(out+'/checks/raw-staged-diff-check.stderr.txt',raw.stderr||'',{flag:'wx'});
// Separate original bytes from new maintainer-authored metadata for meaningful whitespace diagnostics.
const authored=initial.filter(f=>f==='implementation-state.json'||(f.startsWith(prefix)&&!f.startsWith(prefix+'independent-review/')));
const clean=spawnSync('git',['diff','--cached','--check','--',...authored],{cwd:root,encoding:'utf8',maxBuffer:40e6});assert.equal(clean.status,0,clean.stdout+clean.stderr);
write('checks/staged-whitespace-01.json',{raw:{command:'git diff --cached --check',exitCode:raw.status,stdout:'raw-staged-diff-check.stdout.txt',stderr:'raw-staged-diff-check.stderr.txt',diagnosticLines:(raw.stdout||'').split('\n').filter(Boolean).length},authoredMetadata:{exitCode:clean.status,checkedPaths:authored},disposition:raw.status===0?'No whitespace diagnostic':'Original raw reviewer/Coordinator bytes preserved exactly; diagnostics retained, no formatting or normalization performed. Newly authored maintainer metadata checked separately.'});
const rawReport=read(out+'/independent-review/INDEPENDENT_REVIEW_RESULT.json'),rejection=read(out+'/independent-review/network-approval-rejection-01.json');
const manifestFiles=[...walk(out).map(f=>f.slice(root.length+1)),...coord.files.map(r=>r.file),'implementation-state.json'].map(identity).sort((a,b)=>a.file.localeCompare(b.file));
write('manifest-01.json',{reviewedI:I,reviewedR:R,files:manifestFiles,rawReviewObjects:331,coordinatorObjects:coord.files.length,excludes:['manifest-01.json self identity','persistence-01.json binds this manifest','stage-final.paths mechanical allowlist','postcommit-01.json written after commit and intentionally untracked'],purpose:'Complete persisted bytes/hash list; original report and original manifest remain separate and unchanged'});
write('persistence-01.json',{actionKey:'yeataro/Grape:S05:review06-persistence:6c3a734:01',packetId:'S05-REVIEW06-PERSISTENCE-01',status:'PERSISTED_BLOCKED_REVIEW_STOP_WRITING',metadataCommit:'Exact commit introducing this file; resolve git log -1 --format=%H -- production/evidence/s05/review-06/persistence-01.json. This metadata descendant is not independently reviewed product.',reviewId:rawReport.reviewId,author:rawReport.reviewerIdentity,reviewedI:I,reviewedR:R,verdict:rawReport.verdict,classification:'WF_PERMISSION',gap:rawReport.requiredEvidenceGaps[0],rawReport:identity(prefix+'independent-review/INDEPENDENT_REVIEW_RESULT.json'),rawManifest:identity(prefix+'independent-review/supporting-evidence-manifest-01.json'),relocation:identity(prefix+'relocation-01.json'),preservation:identity(prefix+'preservation-01.json'),manifest:identity(prefix+'manifest-01.json'),checks:identity(prefix+'checks/results-01.json'),whitespace:identity(prefix+'checks/staged-whitespace-01.json'),rawCopied:331,sourceConfigVerified:131,coordinatorPreparedFiles:coord.files.length,preview:'Staged assets/guide/ZIP preserved only; no deployment or service execution',productAcceptance:'NOT_GRANTED',S05:'ACTIVE_INCOMPLETE',blockingOperation:rejection.requestedAction,exactAutomaticRejectionReason:rejection.reason,permissionStatus:'Pending; no Human response inferred; missing checks not executed by writer',counters:{repairAttempt:1,unsuccessfulTechnicalReviewRounds:0,globalReviewSequence:6,persistenceAttempt:1,retriesUsed:0},unchanged:['I6 implementationBaseline','build','activeSlices','acceptedEvidence','historical acceptance/PASS/FAIL','README','source/tests/tools/config/dependencies','handoff','references/debug.log/unrelated untracked data'],next:'Coordinator reconciles persistence; trusted authorization prerequisite remains before original reviewer resumes only missing exact-IP checks. No actor/transport substitution or historicalPASS reuse.',writerState:'STOP_WRITING'});
const final=['implementation-state.json',...coord.files.map(r=>r.file),...walk(out).map(f=>f.slice(root.length+1))];final.push(prefix+'stage-final.paths');assert.equal(new Set(final).size,final.length);assert.ok(final.every(allowed));fs.writeFileSync(out+'/stage-final.paths',final.join('\n')+'\n',{flag:'wx'});
git('-c','core.autocrlf=false','add','-f','--pathspec-from-file='+out+'/stage-final.paths');assert.deepEqual(git('diff','--cached','--name-only','-z').split('\0').filter(Boolean).sort(),[...final].sort());
const index=git('ls-files','-s','-z').split('\0').filter(Boolean);for(const x of index){const[h,f]=x.split('\t');assert.equal(blob(fs.readFileSync(root+'/'+f)),h.split(' ')[1],f);}
const commit=git('commit','-m','Preserve blocked S05 review6 and pending permission evidence'),P=git('rev-parse','HEAD').trim();assert.equal(git('rev-parse','HEAD^').trim(),R);assert.equal(git('diff','--name-only').trim(),'');assert.equal(git('diff','--cached','--name-only').trim(),'');
const committed=git('ls-files','-s','-z').split('\0').filter(Boolean);for(const x of committed){const[h,f]=x.split('\t');assert.equal(blob(fs.readFileSync(root+'/'+f)),h.split(' ')[1],f);}for(const r of rel.files)assert.equal(identity(r.destination).sha256,r.sha256);for(const r of sources.files)assert.equal(identity(r.file).sha256,r.sha256);for(const r of pre.untracked)assert.equal(identity(r.file).sha256,r.sha256);
write('postcommit-01.json',{persistenceCommit:P,parent:R,reviewedI:I,reviewedR:R,commitSubject:commit.split('\n')[0],stagedPaths:final.length,allTrackedGitBlobAndDiskVerified:committed.length,rawCopiedGitAndDiskVerified:331,sourceConfigVerified:131,originalUntrackedVerified:pre.untracked.length,cleanTrackedAndIndex:true,manifest:identity(prefix+'manifest-01.json'),relocation:identity(prefix+'relocation-01.json'),preservation:identity(prefix+'preservation-01.json'),persistence:identity(prefix+'persistence-01.json'),receiptStorage:'This actual postcommit receipt is intentionally untracked; all referenced preservation evidence is committed in P.',verdict:'BLOCKED/WF_PERMISSION',writerState:'STOP_WRITING'});
console.log(JSON.stringify({...read(out+'/postcommit-01.json'),postcommit:identity(prefix+'postcommit-01.json')},null,2));
