// Evidence-only preservation helper. No browser, network or product execution.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
import {validateImplementationState} from '../../../../handoff/tools/check-implementation-state.mjs';
const root='C:/Users/user/source/Grape',out=root+'/production/evidence/s05/review-06',R='6c3a734325d0db2d924356a9614e971d80a966c8',I='aa4c86e20b0b4b54218b9992921578e7f24a28a2';
const sha=b=>createHash('sha256').update(b).digest('hex'),blob=b=>createHash('sha1').update(Buffer.from('blob '+b.length+'\0')).update(b).digest('hex'),read=f=>JSON.parse(fs.readFileSync(f,'utf8')),git=(...a)=>execFileSync('git',a,{cwd:root,encoding:'utf8',maxBuffer:120e6}),write=(n,v)=>fs.writeFileSync(out+'/'+n,JSON.stringify(v,null,2)+'\n',{flag:'wx'}),identity=f=>{const b=fs.readFileSync(root+'/'+f);return{file:f,bytes:b.length,sha256:sha(b)}};
const packetFile='production/evidence/coordinator/s05/review-06/persistence-packet-01.json',p=read(root+'/'+packetFile);assert.equal(sha(fs.readFileSync(root+'/'+packetFile)),'d39912eb992ad18478f1ee2f5c96661b412e76042697aaba404ae9ba5260a78b');assert.equal(git('rev-parse','HEAD').trim(),R);assert.equal(git('diff','--name-only').trim(),'');assert.equal(git('diff','--cached','--name-only').trim(),'');assert.ok(!fs.existsSync(out+'/start-01.json'),'No duplicate action');
const verify=(base,r)=>{const file=path.resolve(base,r.file),b=fs.readFileSync(file);assert.equal(b.length,r.bytes,file);assert.equal(sha(b),r.sha256,file);return b;};
for(const r of [...p.inputRefs,p.authorizationRef])verify(root,r);
const report=read(path.join(p.rawReview.root,p.rawReview.report.file)),manifest=read(path.join(p.rawReview.root,p.rawReview.manifest.file));assert.equal(report.reviewedI,I);assert.equal(report.reviewedR,R);assert.equal(report.verdict,'BLOCKED');assert.equal(report.requiredEvidenceGaps[0].id,'S05-DRAG-FR-GAP-001');assert.equal(report.requiredEvidenceGaps[0].classification,'WF_PERMISSION');assert.equal(manifest.files.length,329);
const sources=read(root+'/production/evidence/s05/drag-performance-repair-01/source-config-manifest-01.json');assert.equal(sources.files.length,131);for(const r of sources.files)verify(root,r);
const tracked=git('ls-files','-s','-z').split('\0').filter(Boolean).map(x=>{const[h,f]=x.split('\t'),b=fs.readFileSync(root+'/'+f);assert.equal(blob(b),h.split(' ')[1],f);return{file:f,bytes:b.length,sha256:sha(b),gitBlob:h.split(' ')[1]}});
const untracked=git('ls-files','--others','--exclude-standard','-z').split('\0').filter(Boolean).filter(f=>!f.startsWith('production/evidence/s05/review-06/')).map(identity);
write('preimages-01.json',{head:R,tracked,untracked});
write('start-01.json',{actionKey:p.actionKey,packetId:p.packetId,startedAt:new Date().toISOString(),expectedHead:R,writer:p.writer,attempt:1,retriesUsed:0,scope:'Evidence and permitted state prose only; no network/service/product work',rawReportBinding:{reviewId:report.reviewId,reviewedI:I,reviewedR:R,verdict:report.verdict},counters:p.findingGroup,packet:identity(packetFile)});
const raws=[p.rawReview.report,p.rawReview.manifest,...manifest.files],seen=new Set(),rows=[];for(const r of raws){assert.ok(!path.isAbsolute(r.file));const rel=path.normalize(r.file);assert.ok(!rel.startsWith('..'+path.sep)&&rel!=='..');assert.ok(!seen.has(rel));seen.add(rel);const src=path.resolve(p.rawReview.root,rel);assert.ok(src.startsWith(path.resolve(p.rawReview.root)+path.sep));assert.ok(fs.lstatSync(src).isFile()&&!fs.lstatSync(src).isSymbolicLink());const b=verify(p.rawReview.root,r),dest=p.rawReview.destination+r.file;assert.ok(!fs.existsSync(root+'/'+dest));fs.mkdirSync(path.dirname(root+'/'+dest),{recursive:true});fs.writeFileSync(root+'/'+dest,b,{flag:'wx'});rows.push({source:src,destination:dest,bytes:b.length,sha256:sha(b)});}
write('relocation-01.json',{reviewId:report.reviewId,reviewer:report.reviewerIdentity,originalRoot:p.rawReview.root,verdict:report.verdict,reviewedI:I,reviewedR:R,classification:'WF_PERMISSION',copyCount:rows.length,rule:'Original relative paths, bytes, authorship, verdict, null identifiers, whitespace and CRLF preserved; relocation is separately authored maintainer metadata',files:rows});
const coordinatorDirs=['production/evidence/coordinator/s05/review-06','production/evidence/coordinator/s05/preview-05'];const coordinator=coordinatorDirs.flatMap(dir=>fs.readdirSync(root+'/'+dir).filter(n=>fs.lstatSync(root+'/'+dir+'/'+n).isFile()).map(n=>identity(dir+'/'+n)));
const pr=read(root+'/production/evidence/coordinator/s05/review-06/persistence-parent-result-01.json');assert.equal(pr.actionKey,p.actionKey);assert.equal(pr.actualPersistenceDispatches,1);assert.equal(pr.writer.canonicalAgent,p.writer.canonicalAgent);assert.equal(pr.expectedStartingHead,R);assert.equal(pr.packet.sha256,sha(fs.readFileSync(root+'/'+packetFile)));
write('coordinator-inputs-01.json',{files:coordinator,attribution:'Original Coordinator/parent receipts and preview preparation bytes; preserved without execution or reinterpretation. preview-05 is STAGED_NOT_DEPLOYED, not a deployment claim.',parentDispatches:pr.actualPersistenceDispatches,networkPermission:'Pending; no Human answer inferred'});
const oldText=fs.readFileSync(root+'/implementation-state.json','utf8'),state=JSON.parse(oldText),original=structuredClone(state);
const replacement=`Performance diagnosis and bounded repair self-checks are complete. Original Fresh Reviewer /root/s05_drag_review_01 report S05-DRAG-PERFORMANCE-FR-6c3a734-01 at I ${I} / R ${R} is BLOCKED / WF_PERMISSION; S05-DRAG-FR-GAP-001 remains OPEN because two exact LAN/Tailscale static-archive checks were not executed after automatic approval rejected the claimed payload/destination authorization. No product defect was found in executed scope; completed probes are not independent PASS. Network authorization question is pending; no answer inferred. Human acceptance remains NOT_GRANTED. RepairAttempt1 / unsuccessfulTechnicalReviewRounds0 / globalReviewSequence6 are retained.`;
for(const d of state.decisionReferences.filter(x=>['DEC-GRAPE-003','AC-GRAPE-002'].includes(x.id))){const needle='Performance diagnosis and bounded repair self-checks are complete; new exact independent review and Human acceptance pending.';assert.ok(d.scope.includes(needle));d.scope=d.scope.replace(needle,replacement);}
for(const k of Object.keys(original).filter(k=>k!=='decisionReferences'))assert.deepEqual(state[k],original[k],k);assert.equal(state.implementationBaseline.revision,I);assert.deepEqual(state.activeSlices,['S05']);
const baseline={slices:read(root+'/handoff/data/slices.json').slices,gates:read(root+'/handoff/data/gates.json').gates},validated=validateImplementationState(state,baseline,f=>fs.readFileSync(root+'/'+f));assert.equal(validated.status,'CURRENT_RECORD_VALID');assert.equal(validated.errors.length,0);
const eol=oldText.includes('\r\n')?'\r\n':'\n',next=(JSON.stringify(state,null,2)+'\n').replaceAll('\n',eol);fs.writeFileSync(out+'/state-candidate.tmp',next,{flag:'wx'});assert.deepEqual(JSON.parse(fs.readFileSync(out+'/state-candidate.tmp','utf8')),state);fs.renameSync(out+'/state-candidate.tmp',root+'/implementation-state.json');
write('state-preservation-01.json',{validatedBeforeAtomicReplacement:true,status:validated.status,errors:validated.errors,changedFields:['decisionReferences[DEC-GRAPE-003].scope','decisionReferences[AC-GRAPE-002].scope'],unchangedKeys:Object.keys(original).filter(k=>k!=='decisionReferences'),implementationI:I,build:state.build,activeSlices:state.activeSlices,acceptedEvidenceUnchanged:true,beforeSha256:sha(Buffer.from(oldText)),afterSha256:sha(fs.readFileSync(root+'/implementation-state.json')),reviewId:report.reviewId,verdict:'BLOCKED',classification:'WF_PERMISSION',gap:'S05-DRAG-FR-GAP-001',productAcceptance:'NOT_GRANTED',updatedAt:'Existing state timestamp preserved; actual persistence time is recorded in start-01.json'});
console.log(JSON.stringify({copied:rows.length,trackedPreimages:tracked.length,untrackedPreimages:untracked.length,coordinatorFiles:coordinator.length,sourceConfig:131,state:'CURRENT_RECORD_VALID',verdict:'BLOCKED/WF_PERMISSION'}));
